MADMAC=$(JAGPATH)/bin/mac
ALN=$(JAGPATH)/bin/aln
WDB=$(JAGPATH)/bin/wdb
RDB=$(JAGPATH)/bin/rdbjag
LO=$(JAGPATH)/bin/lo -p $(PARIRQ)
JCP=$(JAGPATH)/bin/jcp

CC=m68k-atari-mint-gcc
LIB=$(JAGPATH)/lib/lib
INCL=-I$(JAGPATH)/lib/include

CATNIPLO=$(JAGPATH)/bin/lo_catnip
CATNIPTTY?=/dev/ttyUSB0

STADDR=4000
ALNFLAGS=-a $(STADDR) x x -rq -v -v -v -w -y $(LIB)
MACFLAGS=-fb -v
CFLAGS=-mcpu=68000 -Wall -fomit-frame-pointer -O2 -msoft-float -funroll-loops $(INCL)
