MADMAC=$(JAGPATH)/bin/mac
ALN=$(JAGPATH)/bin/aln
WDB=$(JAGPATH)/bin/wdb
RDB=$(JAGPATH)/bin/rdbjag
LO=$(JAGPATH)/bin/lo -p $(PARIRQ)
JCP=$(JAGPATH)/bin/jcp
CONVERTER=$(JAGPATH)/bin/converter
OCAML=ocaml
LZ77=$(JAGPATH)/bin/lz77

CC=m68k-atari-mint-gcc
LIB=$(JAGPATH)/lib/lib
INCL=$(JAGPATH)/lib/include

CATNIPLO=$(JAGPATH)/bin/lo_catnip
CATNIPTTY?=/dev/ttyUSB0

ALNFLAGS=-rq -v -w -y $(LIB)
MACFLAGS=-fb -v -i$(INCL)
CFLAGS=-mcpu=68000 -Wall -fomit-frame-pointer -O2 -msoft-float -funroll-loops -I$(INCL)
